services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  web:
    image: laravel-mongo-web
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - .:/var/www
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Acesse pelo localhost:8080
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
